### ISSUE TITLE
iojs and gulp-sass

### ISSUE THREAD

**Issue by aj0strow** [dlmanning/gulp-sass#175]
Something's broken, and I'm not sure what. I think it's `gulp-sass` but it could be something else entirely. If you have a moment to give this stack trace a look, I'd really appreciate it, thank you. 

The package builds correctly, but the the task fails. 

```sh
[22:10:48] 'stylesheets' errored after 8.6 ms
[22:10:48] Error: Module did not self-register.
  at Error (native)
  at Module.load (cwd/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:296:12)
  at Module.require (module.js:351:17)
  at require (module.js:370:17)
  at Object.<anonymous> (cwd/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:211:15)
  at Module._compile (module.js:446:26)
  at Object.Module._extensions..js (module.js:464:10)
  at Module.load (cwd/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:296:12)
  at Module.require (module.js:351:17)
  at require (module.js:370:17)
  at Object.<anonymous> (cwd/node_modules/gulp-sass/index.js:3:17)
  at Module._compile (module.js:446:26)
  at Object.Module._extensions..js (module.js:464:10)
  at Module.load (cwd/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:296:12)
  at Module.require (module.js:351:17)
  at require (module.js:370:17)
  at Object.defineProperty.get (cwd/node_modules/gulp-load-plugins/index.js:49:18)
  at cwd/gulpfile.coffee:149:10
  at Gulp.<anonymous> (cwd/gulpfile.coffee:99:10)
  at module.exports (cwd/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (cwd/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (cwd/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (cwd/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at runNextSet (cwd/node_modules/run-sequence/index.js:74:16)
  at Gulp.onTaskEnd (cwd/node_modules/run-sequence/index.js:63:5)
  at Gulp.emit (events.js:117:20)
  at Gulp.Orchestrator._emitTaskDone (cwd/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at cwd/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (cwd/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (cwd/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at cwd/node_modules/del/index.js:54:4
  at callback (cwd/node_modules/del/node_modules/each-async/index.js:38:4)
  at cwd/node_modules/del/node_modules/each-async/node_modules/onetime/index.js:20:12
  at FSReqWrap.CB [as oncomplete] (cwd/node_modules/del/node_modules/rimraf/rimraf.js:68:5)

```

**Comment by aj0strow** [comment]
The stack trace points to `gulpfile.coffee:149:10` which is the `gulp-sass` call.

```coffee
plugins.sass(includePaths: [
    "#{ __dirname }/bower_components/bootstrap-sass-official/assets/stylesheets"
    "#{ __dirname }/stylesheets/mixins"
  ])
```

**Comment by dlmanning** [comment]
node-sass (for which gulp-sass is a wrapper) does not yet support io.js. https://github.com/sass/node-sass/issues/627

**Comment by aj0strow** [comment]
Ah that makes sense. Thank you.

**Comment by suenot** [comment]
compatible with io.js is interesting

**Comment by benjamindean** [comment]
Latest version of gulp-sass refused to work with ``io.js 1.5.1``. However, I found a solution. Edited ``/node_modules/gulp-sass/package.json`` and set ``node-sass`` dependency version to ``*``. Then, ``npm update`` right from gulp-sass directory.
Looks like its working fine with ```node-sass@3.0.0-dev```.

**Comment by dlmanning** [comment]
@benjamindean Could you elaborate on "refused to work with" ?

**Comment by benjamindean** [comment]
Well, here is, probably, a bug in installation script of `node-sass`:
`Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-node-1.5/binding.node`

It's looking for *linux-x64-node-{node_version}/binding.node* file. The latest available is, obviously, *linux-x64-node-0.12/binding.node*. That's why I have to install `node-sass` manually.

I am using `iojs@1.5.1` and `npm@2.7.0`.

**Comment by rstacruz** [comment]
I think this issue should be reopened.

**Comment by dlmanning** [comment]
@benjamindean @rstacruz Problem is I can't replicate this error, so it's looking to me like a local configuration thing. Are you able to install node-sass on its own?

**Comment by rstacruz** [comment]
OSX Mavericks here with iojs 1.3.0 — it seems node-sass 2.x doesn't install on iojs. however, the newer node-sass 3.0.x is fine.

```
› iojs --version
v1.3.0

› npm install gulp-sass
(...snip...)

> node-sass@2.0.1 postinstall /···/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

module.js:322
    throw err;
          ^
Error: Cannot find module '/···/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:320:15)
   (...snip...)
Build failed
```

**Comment by benjamindean** [comment]
@dlmanning Here is the latest [node-sass-binaries](https://github.com/sass/node-sass-binaries/releases/tag/v2.0.1), which contains `linux-x64-iojs-1.2` binary, what means compatibility with iojs 1.2 and above. In some cases, installation script detects iojs as node and searching wrong version. Maybe it depends on a way of installing iojs? I just replaced node binaries and that's all.
